version: '3.8'

services:
  # 1. DB (postgres)
  db:
    image: postgres:15-alpine
    container_name: tteokguk-postgres
    restart: always
    ports:
      - "5432:5432"
    shm_size: 128mb
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db_data:/var/lib/postgresql/data

  # 2. redis 추가
  redis:
    image: redis:alpine
    container_name: tteokguk-redis
    ports:
      - "6379:6379"
    restart: always

  # 3. server
  app:
    container_name: tteokguk-backend
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI:http://localhost:5173/auth/google/callback}
